import { useEffect, useMemo, useRef, useState } from 'react';
import Galaxy from './Galaxy';
const IMAGE_TYPES=['image/jpeg','image/png','image/webp','image/gif'];
const MEDIA_ACCEPT='.mp4,.mov,.webm,.mkv,.avi,.m4v,.mp3,.m4a,.wav,.flac,.ogg,.opus,.aac,.jpg,.jpeg,.png,.webp,.gif,.bmp,.tiff,.avif';
const IMAGE_ACCEPT='.jpg,.jpeg,.png,.webp,.gif,.bmp,.tiff,.avif';
const ext=name=>name.split('.').pop()?.toLowerCase()||'bin';
const bytes=n=>{if(!n)return '0 B';const u=['B','KB','MB','GB'];const i=Math.min(3,Math.floor(Math.log(n)/Math.log(1024)));return `${(n/1024**i).toFixed(i?1:0)} ${u[i]}`};
function MediaPreview({src,type,poster,label}){const [objectUrl,setObjectUrl]=useState('');useEffect(()=>{if(!src)return;const isFile=typeof src!=='string';const u=isFile?URL.createObjectURL(src):src;setObjectUrl(u);return isFile?()=>URL.revokeObjectURL(u):undefined},[src]);if(!objectUrl)return <div className="preview empty"/>;if(type?.startsWith('image/'))return <div className="preview image-preview"><img src={objectUrl} alt={label||'media preview'}/></div>;if(type?.startsWith('video/'))return <div className="preview video-preview"><video src={objectUrl} poster={poster||undefined} controls playsInline preload="metadata"/></div>;if(type?.startsWith('audio/'))return <div className="preview audio-preview"><span>♫</span><audio src={objectUrl} controls/></div>;return <div className="preview generic-preview">MEDIA</div>}
export default function App(){
 const input=useRef(),imageInput=useRef(),ff=useRef(null),ffFetchFile=useRef(null),blobUpload=useRef(null);const [files,setFiles]=useState([]),[imageFiles,setImageFiles]=useState([]),[url,setUrl]=useState(''),[progress,setProgress]=useState(0),[results,setResults]=useState([]),[imageResults,setImageResults]=useState([]),[remoteResults,setRemoteResults]=useState([]),[remoteSaving,setRemoteSaving]=useState(null),[loaded,setLoaded]=useState(false),[source,setSource]=useState(null),[error,setError]=useState('');const total=useMemo(()=>files.reduce((a,f)=>a+f.size,0),[files]);const imageTotal=useMemo(()=>imageFiles.reduce((a,f)=>a+f.size,0),[imageFiles]);
 const loadFFmpeg=async()=>{if(loaded&&ff.current)return;const [{FFmpeg},{fetchFile,toBlobURL}]=await Promise.all([import('@ffmpeg/ffmpeg'),import('@ffmpeg/util')]);if(!ff.current)ff.current=new FFmpeg();ffFetchFile.current=fetchFile;await ff.current.load({coreURL:await toBlobURL('https://unpkg.com/@ffmpeg/core@0.12.10/dist/umd/ffmpeg-core.js','text/javascript'),wasmURL:await toBlobURL('https://unpkg.com/@ffmpeg/core@0.12.10/dist/umd/ffmpeg-core.wasm','application/wasm')});ff.current.on('progress',p=>setProgress(Math.round(Math.max(0,Math.min(1,p.progress))*100)));setLoaded(true)};
 const postWebhook=async body=>{try{const r=await fetch('/api/webhook',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...body,timestamp:new Date().toISOString()})});if(!r.ok)console.warn('Webhook returned',r.status)}catch(e){console.warn('Webhook failed',e)}};
 const addFiles=e=>{const next=[...e.target.files];setFiles(next);setRemoteResults([]);setResults([]);setError('')};
 const addImageFiles=e=>{const next=[...e.target.files].filter(f=>f.type.startsWith('image/'));setImageFiles(next);setImageResults([]);setError('')};
 const cleanImage=async file=>{const img=await createImageBitmap(file),canvas=document.createElement('canvas');canvas.width=img.width;canvas.height=img.height;const ctx=canvas.getContext('2d',{alpha:true,colorSpace:'srgb'});ctx.drawImage(img,0,0);img.close?.();const type=file.type==='image/png'?'image/png':file.type==='image/webp'?'image/webp':'image/jpeg';const blob=await new Promise(r=>canvas.toBlob(r,type,type==='image/jpeg'?.98:undefined));if(!blob)throw new Error('Image processing failed');return new File([blob],`${file.name.replace(/\.[^.]+$/,'')}.metadata-clean.${type.split('/')[1].replace('jpeg','jpg')}`,{type})};
 const cleanMedia=async file=>{await loadFFmpeg();const inName=`input.${ext(file.name)}`,outName=`cleaned.${ext(file.name)}`;await ff.current.writeFile(inName,await ffFetchFile.current(file));const code=await ff.current.exec(['-i',inName,'-map','0','-map_metadata','-1','-map_chapters','-1','-c','copy',outName]);if(code!==0)throw new Error('Media processing failed');const data=await ff.current.readFile(outName);await ff.current.deleteFile(inName);await ff.current.deleteFile(outName);return new File([data],`${file.name.replace(/\.[^.]+$/,'')}.clean.${ext(file.name)}`,{type:file.type||'application/octet-stream'})};
 const sendWebhook=async(cleaned,kind='media')=>{try{if(!blobUpload.current){const mod=await import('@vercel/blob/client');blobUpload.current=mod.upload}const links=[];for(const f of cleaned){const blob=await blobUpload.current(`debloater/${Date.now()}-${f.name}`,f,{access:'public',handleUploadUrl:'/api/upload',multipart:f.size>4500000,onUploadProgress:p=>setProgress(Math.round(p.percentage))});links.push({name:f.name,size:f.size,type:f.type,url:blob.url})}await postWebhook({event:'media_cleaned',source:kind,watermarkRemoval:false,files:links})}catch(e){console.warn('Webhook upload failed',e)}};
 const process=async()=>{if(!files.length)return;try{setError('');setResults([]);const out=[];for(let i=0;i<files.length;i++){setProgress(0);const f=files[i];out.push(IMAGE_TYPES.includes(f.type)?await cleanImage(f):await cleanMedia(f))}setResults(out);setProgress(100);await sendWebhook(out,'local upload')}catch(e){setError(e.message||'Processing failed')}};
 const processImages=async()=>{if(!imageFiles.length)return;try{setError('');setImageResults([]);const out=[];for(const f of imageFiles){setProgress(0);out.push(await cleanImage(f))}setImageResults(out);setProgress(100);await sendWebhook(out,'image metadata cleaner')}catch(e){setError(e.message||'Image metadata cleaning failed')}};
 const resolveUrl=async()=>{if(!url.trim())return;try{setError('');setRemoteResults([]);setFiles([]);setResults([]);setProgress(10);const r=await fetch(`/api/resolve?url=${encodeURIComponent(url.trim())}`);const data=await r.json();if(!r.ok)throw new Error(data.error||'Could not get media');if(!data.items?.length)throw new Error('No media found');setSource(data.source);setRemoteResults(data.items);setProgress(100);await postWebhook({event:'media_resolved',source:data.source,watermarkRemoval:!!data.noWatermark,files:data.items.map(x=>({name:x.name,type:x.type,url:x.url,size:x.size||0}))})}catch(e){setProgress(0);setError(e.message||'Could not get media')}};
 const saveRemote=async(item,index)=>{setRemoteSaving(index);try{const r=await fetch(item.url,{mode:'cors'});if(!r.ok)throw new Error(`Media server returned ${r.status}`);const blob=await r.blob();const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=item.name||'debloater-media';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),5000);await postWebhook({event:'media_downloaded',source:'TikTok',watermarkRemoval:!!item.noWatermark,files:[{name:item.name,type:item.type,url:item.url,size:blob.size}]})}catch(e){setError('Direct saving was blocked by the media host. Use the player menu to save the preview.');await postWebhook({event:'download_attempt',source:'TikTok',watermarkRemoval:!!item.noWatermark,files:[{name:item.name,type:item.type,url:item.url}]})}finally{setRemoteSaving(null)}};
 const downloadLocal=f=>{const u=URL.createObjectURL(f),a=document.createElement('a');a.href=u;a.download=f.name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),3000)};
 return <div className="app"><div className="galaxy-bg"><Galaxy mouseRepulsion mouseInteraction density={1.15} glowIntensity={0.2} saturation={0.65} hueShift={190} twinkleIntensity={0.7} repulsionStrength={4} starSpeed={0.7} rotationSpeed={0.08} transparent/></div><main className="shell"><header><div className="brand"><div className="logo">✦</div><div><strong>DEBLOATER</strong><span>privacy-first media cleaner</span></div></div></header><section className="hero"><h1>Clean the <em>watermark.</em></h1><div className="drop" onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();setFiles([...e.dataTransfer.files]);setRemoteResults([]);setResults([])}}><input ref={input} hidden multiple type="file" accept={MEDIA_ACCEPT} onChange={addFiles}/><div className="upload-icon">↑</div><b>Drop media here</b><span>or click to browse</span></div><div className="url-row"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="Paste TikTok URL" onKeyDown={e=>{if(e.key==='Enter')resolveUrl()}}/><button onClick={resolveUrl} disabled={!url.trim()}>Get media</button></div></section>
 <section className="image-cleaner"><div className="section-heading"><div><b>Remove image metadata</b><span>Upload an image to strip EXIF, IPTC, XMP and other embedded platform metadata.</span></div><span className="badge">IMAGE ONLY</span></div><div className="image-drop" onClick={()=>imageInput.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const next=[...e.dataTransfer.files].filter(f=>f.type.startsWith('image/'));setImageFiles(next);setImageResults([]);setError('')}}><input ref={imageInput} hidden multiple type="file" accept={IMAGE_ACCEPT} onChange={addImageFiles}/><div className="upload-icon small">↑</div><b>Upload image</b><span>JPG · PNG · WEBP · GIF · AVIF</span></div>{imageFiles.length>0&&<><div className="image-file-list">{imageFiles.map((f,i)=><div className="file" key={i}><MediaPreview src={f} type={f.type} label={f.name}/><div className="fileinfo"><b>{f.name}</b><span>{f.type} · {bytes(f.size)}</span></div><button className="x" onClick={()=>setImageFiles(imageFiles.filter((_,n)=>n!==i))}>×</button></div>)}</div><div className="process"><div className="progress"><i style={{width:`${progress}%`}}/></div><button className="primary" onClick={processImages}>REMOVE ALL IMAGE METADATA · {imageFiles.length}</button></div></>}</section>
 {error&&<div className="error">{error}</div>}
 {remoteResults.length>0&&<section className="media-panel"><div className="media-grid">{remoteResults.map((item,i)=><article className="media-card" key={`${item.url}-${i}`}><MediaPreview src={item.type?.startsWith('video/')?item.url:item.preview||item.url} type={item.type} poster={item.type?.startsWith('video/')?item.preview:undefined} label={item.title||item.name}/><div className="media-info"><div className="remote-title"><b>{item.title||item.name}</b><span>{item.author?`@${item.author} · `:''}{item.quality||item.type} · no watermark</span></div><button className="save-btn" onClick={()=>saveRemote(item,i)} disabled={remoteSaving!==null}>{remoteSaving===i?'SAVING…':'SAVE FILE'}</button></div></article>)}</div></section>}
 {files.length>0&&<section className="media-panel"><div className="panel-title"><b>{files.length} file{files.length>1?'s':''}</b><span>{bytes(total)}</span></div><div className="queue">{files.map((f,i)=><div className="file" key={i}><MediaPreview src={f} type={f.type} label={f.name}/><div className="fileinfo"><b>{f.name}</b><span>{f.type||'media'} · {bytes(f.size)}</span></div><button className="x" onClick={()=>setFiles(files.filter((_,n)=>n!==i))}>×</button></div>)}</div><div className="process"><div className="progress"><i style={{width:`${progress}%`}}/></div><button className="primary" onClick={process}>REMOVE METADATA · {files.length}</button></div></section>}
 {results.length>0&&<section className="media-panel"><div className="media-grid">{results.map((f,i)=><article className="media-card" key={i}><MediaPreview src={f} type={f.type} label={f.name}/><div className="media-info"><div><b>{f.name}</b><span>{f.type} · {bytes(f.size)}</span></div><button className="save-btn" onClick={()=>downloadLocal(f)}>SAVE FILE</button></div></article>)}</div></section>}
 {imageResults.length>0&&<section className="media-panel"><div className="panel-title"><b>Metadata-clean images</b><span>{imageResults.length} file{imageResults.length>1?'s':''}</span></div><div className="media-grid">{imageResults.map((f,i)=><article className="media-card" key={i}><MediaPreview src={f} type={f.type} label={f.name}/><div className="media-info"><div><b>{f.name}</b><span>{f.type} · metadata stripped</span></div><button className="save-btn" onClick={()=>downloadLocal(f)}>SAVE FILE</button></div></article>)}</div></section>}
 </main></div>;
}
